export enum UserAction {
    LOGIN = "LOGIN",
    LOGOUT = "LOGOUT",
    ADD_FOOD_ITEM = "ADD_FOOD_ITEM",
    UPDATE_FOOD_ITEM = "UPDATE_FOOD_ITEM",
    DELETE_FOOD_ITEM = "DELETE_FOOD_ITEM",
    VIEW_MENU = "VIEW_MENU",
    VIEW_FEEDBACK = "VIEW_FEEDBACK",
    VIEW_DISCARD_FOOD_ITEM = "VIEW_DISCARD_FOOD_ITEM",
    DELETE_DISCARD_FOOD_ITEM = "DELETE_DISCARD_FOOD_ITEM",
    VIEW_RECOMMENDED_FOOD_ITEM = "VIEW_RECOMMENDED_FOOD_ITEM",
    ROLLED_OUT_ITEM = "ROLLED_OUT_ITEM",
    FINALIZE_FOOD_ITEM = "FINALIZE_FOOD_ITEM",
    VIEW_NOTIFICATION = "VIEW_NOTIFICATION",
    VOTE_FOR_FOOD_ITEM = "VOTE_FOR_FOOD_ITEM",
    GIVE_FEEDBACK = "GIVE_FEEDBACK",
    VIEW_FINAL_MENU = "VIEW_FINAL_MENU",
    GIVE_DETAILED_FEEDBACK = "GIVE_DETAILED_FEEDBACK",
    UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE"  
  }
  